## Generated by SimInf (v6.1.0.9000) 2018-09-05 13:38 */

##' Class \code{SLHV}
##'
##' Class to handle the \code{SLHV} \code{SimInf_model}.
##' @export
setClass("SLHV", contains = "SimInf_model")

##' Create a model for the SimInf framework
##'
##' Create a model to be used by the SimInf framework.
##' @param u0 A data.frame with the initial state in each node.
##' @param tspan A vector (length >= 2) of increasing time points
##'     where the state of each node is to be returned.
##' @param events A data.frame with scheduled events.
##' @param gdata A named numeric vector with rate-constants for the
##'     model.
##' @import SimInf
##' @import methods
##' @export
##' @examples
##' ## Please add example(s) how to use the model
SLHV <- function(u0 = NULL, tspan = NULL, events = NULL, 
                 phi = NULL, end_t1 = NULL, end_t2 = NULL, end_t3 = NULL, end_t4 = NULL,
                 gdata = NULL) {
    compartments <- c("S", "L", "H", "V")
    parameters <- c("upsilon", "delta", "alpha1", "alpha2", "gamma1", "gamma2", "gamma3", "epsilon", "beta_t1", "beta_t2", "beta_t3", "beta_t4")
    #lpars <- c("phi", "end_t1", "end_t2", "end_t3", "end_t4")

    ## Check u0
    if (is.null(u0))
        stop("'u0' must be specified.")
    if (!is.data.frame(u0))
        u0 <- as.data.frame(u0)
    if (!all(compartments %in% names(u0)))
        stop("Missing columns in u0")
    u0 <- u0[, compartments, drop = FALSE]

    # ## Check ldata
    # if (is.null(ldata))
    #     stop("'ldata' must be specified.")
    # if (!is.numeric(ldata))
    #     stop("'ldata' must be a named numeric vector.")
    # if (!all(lpars %in% names(ldata)))
    #     stop("Missing parameters in 'ldata'")
    # if (ncol(ldata) != nrow(u0))
    #     stop("Number of columns in 'ldata' not equal to number of rows in 'u0'")
    # ldata <- ldata[lpars, ]
    
    phi <- rep(phi, length.out = nrow(u0))
    end_t1 <- rep(end_t1, length.out = nrow(u0))
    end_t2 <- rep(end_t2, length.out = nrow(u0))
    end_t3 <- rep(end_t3, length.out = nrow(u0))
    end_t4 <- rep(end_t4, length.out = nrow(u0))
    ldata <- matrix(as.numeric(c(phi, end_t1, end_t2, end_t3, end_t4)),
                    nrow  = 5, byrow = TRUE)

    ## Check gdata
    if (is.null(gdata))
        stop("'gdata' must be specified.")
    if (!is.numeric(gdata))
        stop("'gdata' must be a named numeric vector.")
    if (!all(parameters %in% names(gdata)))
        stop("Missing parameters in 'gdata'")
    gdata <- gdata[parameters]

    G <- structure(c(1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 
    1, 1, 0, 1, 0, 0, 0, 1), .Dim = c(5L, 5L), .Dimnames = list(c("S -> L", 
    "L -> H", "L -> S", "H -> L", "V -> S"), c("1", "2", "3", "4", 
    "5")))

    S <- structure(c(-1, 1, 0, 0, 0, -1, 1, 0, 1, -1, 0, 0, 0, 1, -1, 
    0, 1, 0, 0, -1), .Dim = 4:5, .Dimnames = list(c("S", "L", "H", 
    "V"), c("1", "2", "3", "4", "5")))

    #E <- structure(numeric(0), .Dim = c(0L, 0L), .Dimnames = list(NULL, 
    #    NULL))

    #N <- structure(integer(0), .Dim = c(0L, 0L))

    # Specify E matrix (for external transfers)
    E <- matrix(c(1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1,
                        1, 1, 1, 1),
                      ncol = 5)
    require(Matrix)
    E <- Matrix(data = E, sparse = T)
    rownames(E) <- c('S', 'L', 'H', 'V')
    colnames(E) <- c(1:5)

    # Specify N matrix (for internal transfers) -- required for vaccination movements between categories
    N <- matrix(c(3, 0, 0, 0,
                  3, 2, 1, 0),
                ncol = 2)
    rownames(N) <- compartments
    colnames(N) <- c(1:2)
    
    model <- SimInf_model(G = G, S = S, E = E, N = N, tspan = tspan,
                          events = events, u0 = u0, ldata = ldata, gdata = gdata)

    as(model, "SLHV")
}

##' Run the model
##'
##' @rdname run-methods
##' @param model The model to run.
##' @param threads Number of threads. Default is NULL, i.e. to use all
##'     available processors.
##' @param solver Which numerical solver to utilize. Default is NULL,
##'     i.e., use the default numerical solver in SimInf.
##' @return SimInf_model with result from simulation.
##' @export
##' @useDynLib SLHV, .registration=TRUE
setMethod("run",
    signature(model = "SLHV"),
    function(model, threads = NULL, solver = NULL)
    {
        methods::validObject(model)
       .Call(SimInf_model_run, model, threads, solver, PACKAGE = "SLHV")
    })
